name: arxiv-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0.4
  - numpy>=1.22.0
  - pandas>=1.4.2
  - matplotlib>=3.5.1
  - seaborn>=0.11.2
  - scikit-learn>=1.0.2
  - jupyter>=1.0.0
  - jupyterlab>=3.3.2
  - nltk>=3.7
  - spacy>=3.4.0
  - gensim>=4.1.2
  - networkx>=2.8.0
  - plotly>=5.6.0
  - pyldavis>=3.3.1
  - transformers>=4.18.0
  - pytorch>=1.11.0
  - huggingface_hub>=0.5.1
  - tqdm>=4.64.0
  - pip:
    - wordcloud>=1.8.1
    - sentence-transformers>=2.2.0
    - umap-learn>=0.5.3
    - bertopic>=0.12.0
    - community>=1.0.0b1
    - pyvis>=0.2.1